version: '3.4'

services:
  ecommerce.api.customers:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6001:80"

  ecommerce.api.orders:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6002:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:C:\Users\ContainerUser\AppData\Roaming\Microsoft\UserSecrets:ro

  ecommerce.api.products:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6003:80"


  ecommerce.api.search:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6004:80"

